dist: xenial   # required for Python >= 3.7
language: python
python:
  - 3.7-dev
  - 3.8-dev
  # Fails with:
  # ImportError: cannot import name 'Mapping' from 'collections' (/home/travis/virtualenv/python3.9-dev/lib/python3.9/collections/__init__.py)
  # - 3.9-dev
  - 3.7
  - 3.8

git:
  depth: 10

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - python -m pip install pipenv
  - make installdeps-dev

script:
  - make check

after_success:
  - |
      if [[ "`python -V`" =~ ^Python\ 3\.8 ]]
      then
        make codecov
      fi

notifications:
  email:
    recipients:
      - 8.slashes@gmail.com
    # Not effective?
    on_pull_requests: false
  webhooks:
    urls:
      - https://3ends.info/webtools/lggr/post
