dist: xenial   # required for Python >= 3.7
language: python
python:
  - 3.7-dev
  - 3.7
  - 3.8
  # - pypy3.7 Not exists

git:
  depth: 10

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - python -m pip install pipenv
  - make installdeps-dev

script:
  - make check

after_success:
  - make codecov

notifications:
  email:
    recipients:
      - 8.slashes@gmail.com
    # Not effective?
    on_pull_requests: false
  webhooks:
    urls:
      - https://3ends.info/webtools/lggr/post
