dist: xenial   # required for Python >= 3.7
language: python
python:
  # - 3.6
  # - 3.7-dev # Fail with:
  # KeyError: <Task finished coro=<BaseEventLoop.run_in_executor() done, defined at /opt/python/3.7-dev/lib/python3.7/asyncio/base_events.py:653> result=False>
  - 3.7
  # - pypy3.6

git:
  depth: 10

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - python -m pip install pipenv
  - make installdeps-dev

script:
  - make check

after_success:
  - make codecov

notifications:
  email:
    recipients:
      - 8.slashes@gmail.com
    # Not effective?
    on_pull_requests: false
  webhooks:
    urls:
      - https://3ends.info/webtools/lggr/post
