[tool.black]
line-length = 88
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # Project specific
  | .*/migrations
)/
'''


[tool.isort]
skip = "tests/"
# Be happy with black formatter
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
lines_between_types = 1
combine_as_imports = true
default_section = "THIRDPARTY"
known_first_party = "tests"
