# Do not use this in production!
[webtools]
ENV = "local"
SECRET_KEY = "i54q%aiq(olufk#+yjg5e#st1r12%#&_ilm$1*rh_6pn0l^96o"
ALLOWED_HOST = "*"
# This is relative path, for absolute path give four slashes
DATABASE_URL = "sqlite:///db.sqlite3"
EXPORT_AS_BOOKMARK_REDIS_URL = "redis://localhost:7799/1"
